version: '2.2'
services:

  bot:
    ports:
      - "433:433"
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      rabbit:
        condition: service_healthy
      mongodb:
        condition: service_started
    links:
      - mongodb
      - rabbit


  rabbit:
    image: docker.io/bitnami/rabbitmq:3.7.8-debian-9
    hostname: rabbit
    volumes:
      - ${RABBITMQ_DATA:-./rabbitmq/data}:/var/lib/rabbitmq
    restart: on-failure
    healthcheck:
      test: "rabbitmqctl node_health_check"
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "5672:5672"
      - "15672:15672"

  mongodb:
    image: mongo:4.0.3
    volumes:
      - "${MDA_MONGODB_DATA:-./mongodb/data}:/data/db"
    ports:
      - "${MDA_MONGODB_PORT:-27017}:27017"
